backend:
  name: github
  branch: main 
  repo: 1574242600/blog-data
  site_domain: nworm.icu
  base_url: https://nworm.icu
  auth_endpoint: admin/oauth
  commit_messages:
    create: "posts: create {{collection}} “{{slug}}”"
    update: "posts: update {{collection}} “{{slug}}”"
    delete: "posts: delete {{collection}} “{{slug}}”"
    uploadMedia: "assets: upload “{{path}}”"
    deleteMedia: "assets: delete “{{path}}”"
    openAuthoring: '{{message}}'

collections:
  - name: "posts"
    label: "文章"
    folder: "content/posts"
    create: true
    slug: "{{fields.slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "作者", name: "author", widget: "string", default: "Nworm" }
      - { label: "发布日期", name: "date", widget: "datetime", date_format: "YYYY-MM-DD HH:mm:ss" }
      - { label: "更新日期", name: "update", widget: "datetime", date_format: "YYYY-MM-DD HH:mm:ss", required: false }
      - { label: "标签", name: "tags", widget: "list", required: false }
      - { label: "草稿", name: "draft", widget: "boolean", default: true }
      - { label: "正文", name: "body", widget: "markdown" }

search: false
media_folder: "/assets"
public_folder: "https://assets.nworm.icu"